export const IMAGES = {
  logo: require("./logo.png"),
  homeUnselected: require("./bottom-bar/home-empty.png"),
  homeSelected: require("./bottom-bar/home-filled.png"),
  searchUnselected: require("./bottom-bar/search-empty.png"),
  searchSelected: require("./bottom-bar/search-filled.png"),
  addUnselected: require("./bottom-bar/add-empty.png"),
  addSelected: require("./bottom-bar/add-filled.png"),
  heartUnselected: require("./bottom-bar/heart-empty.png"),
  heartSelected: require("./bottom-bar/heart-filled.png"),
  userUnselected: require("./bottom-bar/user-empty.png"),
  userSelected: require("./bottom-bar/user-filled.png"),
  menu: require("./menu.png"),
  heartEmpty: require("./heart-empty.png"),
  heartFilled: require("./heart-filled.png"),
  comment: require("./comment.png"),
  send: require("./send.png"),
  saveEmpty: require("./save-empty.png"),
  saveFilled: require("./save-filled.png"),
};
